config/routes.rb
Rails.application.routes.draw do
  resources :sections

end

app/models/section.rb
class Section < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:show, :edit, :update, :destroy]

  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.all.order('created_at')
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
  end

  # GET /sections/new
  def new
    @section = Section.new
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    if @section.state
      @section.state=false
    else
      @section.state=true
    end
    @section.save
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Section state was successfully changed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      params.require(:section).permit(:title, :state, :alarm_on, :alarm_off, :floor)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HAP</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style="overflow-x:hidden;">

<%= yield %>

</body>
</html>

app/views/sections/_form.html.erb
<%= form_for([@section], :html=>{:class=>'form-inline',:autocomplete=>'on'}) do |f| %>
  <% if @section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% @section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, :class=>"input-small"%>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.check_box :state, :class=> "checkbox"%>
  </div>
  <!-- <div class="field form-group">
    <%= f.label :alarm_on %><br>
    <%= f.datetime_select :alarm_on %>
  </div>
  <div class="field form-group">
    <%= f.label :alarm_off %><br>
    <%= f.datetime_select :alarm_off %>
  </div -->
  <div class="field">
    <%= f.label :floor %><br>
    <%= f.text_field :floor, :class=>"input-small" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sections/edit.html.erb
<h1>Editing section</h1>

<%= render 'form' %>

<%= link_to 'Show', @section, :class=>"btn btn-info btn-small"%> |
<%= link_to 'Back', sections_path, :class=>"btn btn-info btn-small"%>

app/views/sections/index.html.erb
<!-- <h1>Add sections</h1> -->

<!--<%= link_to 'Add Section', new_section_path, :class=>"btn btn-primary btn-small"%>-->

<br/>
<br/>
<!-- <h1>Listing sections</h1> -->
<div class="table-responsive">
<table class="table table-hover table-bordered" style="width:90%;margin-left:5%;">
  <thead>
    <tr>
      <th>Title</th>
      <th>State</th>
      <!-- <th>Alarm on</th> -->
      <!-- <th>Alarm off</th> -->
      <th>Floor</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @sections.each do |section| %>
      <tr>
        <td><%= section.title %></td>
        <td>

        <%if !section.state %>
          <%= link_to image_tag("lamp_off.jpg"), section, method: :delete, data: { status: true }%>
        <%else%>
          <%= link_to image_tag("lamp_on.jpg"), section, method: :delete, data: { status: false }%>
        <%end%>
        </td>
        <!-- <td><%= section.alarm_on %></td> -->
        <!-- <td><%= section.alarm_off %></td> -->
        <td><%= section.floor %></td>
        <!-- <td><%= link_to 'Show', section, :class=>"btn btn-info btn-small" %></td> -->
        <td><%= link_to 'Edit', edit_section_path(section), :class=>"btn btn-secondary btn-large" %></td>
        <!-- <td><%= link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' },:class => "btn btn-danger btn-small" %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/sections/new.html.erb
<h1>New section</h1>

<%= render 'form' %>

<%= link_to 'Back', sections_path %>

app/views/sections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @section.title %>
</p>

<p>
  <strong>State:</strong>
  <%= @section.state %>
</p>

<!-- <p>
  <strong>Alarm on:</strong>
  <%= @section.alarm_on %>
</p>

<p>
  <strong>Alarm off:</strong>
  <%= @section.alarm_off %>
</p> -->

<p>
  <strong>Floor:</strong>
  <%= @section.floor %>
</p>

<%= link_to 'Edit', edit_section_path(@section) , :class=>"btn btn-info btn-small"%> |
<%= link_to 'Back', sections_path, :class=>"btn btn-info btn-small" %>